/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PageContent = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
});
export const Pricing = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const CsrInfo = IDL.Record({
  'status' : IDL.Text,
  'explanation' : IDL.Text,
});

export const idlService = IDL.Service({
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllPageContents' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, PageContent))],
      ['query'],
    ),
  'getAllPricingEntries' : IDL.Func([], [IDL.Vec(Pricing)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCsrInfo' : IDL.Func([], [CsrInfo], ['query']),
  'getPageContent' : IDL.Func([IDL.Text], [IDL.Opt(PageContent)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PageContent = IDL.Record({ 'title' : IDL.Text, 'content' : IDL.Text });
  const Pricing = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const CsrInfo = IDL.Record({ 'status' : IDL.Text, 'explanation' : IDL.Text });
  
  return IDL.Service({
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllPageContents' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, PageContent))],
        ['query'],
      ),
    'getAllPricingEntries' : IDL.Func([], [IDL.Vec(Pricing)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCsrInfo' : IDL.Func([], [CsrInfo], ['query']),
    'getPageContent' : IDL.Func([IDL.Text], [IDL.Opt(PageContent)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };