/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Pricing = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Entry = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'imagePath' : IDL.Text,
  'collection' : IDL.Text,
  'description' : IDL.Text,
  'imageAlt' : IDL.Text,
  'price' : IDL.Nat,
});
export const NavigationEntry = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'path' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllPricingEntries' : IDL.Func([], [IDL.Vec(Pricing)], ['query']),
  'getBeeResults' : IDL.Func(
      [],
      [
        IDL.Record({
          'lastTrayResult' : IDL.Opt(IDL.Text),
          'lastHiveResult' : IDL.Opt(IDL.Text),
          'resultsStack' : IDL.Vec(IDL.Text),
          'lastBeeResult' : IDL.Opt(IDL.Text),
        }),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCollections' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Tuple(
            IDL.Nat,
            IDL.Record({
              'id' : IDL.Nat,
              'title' : IDL.Text,
              'path' : IDL.Text,
            }),
          )
        ),
      ],
      ['query'],
    ),
  'getCsrInfo' : IDL.Func(
      [],
      [IDL.Record({ 'status' : IDL.Text, 'explanation' : IDL.Text })],
      ['query'],
    ),
  'getEntriesByCollection' : IDL.Func([IDL.Nat], [IDL.Vec(Entry)], ['query']),
  'getNavigation' : IDL.Func([IDL.Text], [IDL.Vec(NavigationEntry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Pricing = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Entry = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'imagePath' : IDL.Text,
    'collection' : IDL.Text,
    'description' : IDL.Text,
    'imageAlt' : IDL.Text,
    'price' : IDL.Nat,
  });
  const NavigationEntry = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'path' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllPricingEntries' : IDL.Func([], [IDL.Vec(Pricing)], ['query']),
    'getBeeResults' : IDL.Func(
        [],
        [
          IDL.Record({
            'lastTrayResult' : IDL.Opt(IDL.Text),
            'lastHiveResult' : IDL.Opt(IDL.Text),
            'resultsStack' : IDL.Vec(IDL.Text),
            'lastBeeResult' : IDL.Opt(IDL.Text),
          }),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCollections' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Tuple(
              IDL.Nat,
              IDL.Record({
                'id' : IDL.Nat,
                'title' : IDL.Text,
                'path' : IDL.Text,
              }),
            )
          ),
        ],
        ['query'],
      ),
    'getCsrInfo' : IDL.Func(
        [],
        [IDL.Record({ 'status' : IDL.Text, 'explanation' : IDL.Text })],
        ['query'],
      ),
    'getEntriesByCollection' : IDL.Func([IDL.Nat], [IDL.Vec(Entry)], ['query']),
    'getNavigation' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(NavigationEntry)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };